### ISSUE TITLE
Upgraded from Webpack 3 to 4.12 and couldn't get Styleguidist to run.

### ISSUE THREAD

**Issue by jafin** [styleguidist/react-styleguidist#1015]
**Current behavior**

- Using React-Styleguidist 7.0.17
- Windows OS.
- Node 8.9.4

Upgraded Webpack from 3 to 4.12, 
attempting to run Styleguidist produces a DeprecationWarning
(And warns that address is in use, but I don't believe it is)

**To reproduce**

Upgrade a functional setup from webpack 3 to webpack 4.12

I have **process.traceDeprecation = true;** set in the webpack.config.js
Running > npx styleguidist server

```
Starting type checking service...
Using 1 worker with 2048MB memory limit
(node:22480) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
    at new Server (c:\Data\Dev\node_modules\react-styleguidist\node_modules\webpack-dev-server\lib\Server.js:68:12)
    at createServer (c:\Data\Dev\node_modules\react-styleguidist\scripts\create-server.js:28:20)
    at server (c:\Data\Dev\node_modules\react-styleguidist\scripts\server.js:5:21)
    at commandServer (c:\Data\Dev\node_modules\react-styleguidist\bin\styleguidist.js:122:19)
    at Object.<anonymous> (c:\Data\Dev\node_modules\react-styleguidist\bin\styleguidist.js:71:3)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at findNodeScript.then.existing (C:\Users\jfinch\AppData\Roaming\npm\node_modules\npm\node_modules\libnpx\index.js:268:14)
    at <anonymous>
listen EADDRINUSE 0.0.0.0:6060
No type errors found
Version: typescript 2.8.4
```
I tried to update the versions of dev-server in use in styleguidist to: webpack-dev-server@3.1.4 and webpack-dev-middleware@3.1.3 and run again I received:
```

Starting type checking service...
Using 1 worker with 2048MB memory limit
(node:1668) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
    at StyleguidistOptionsPlugin.plugin (c:\Data\Dev\CCSS\src\CCSS\node_modules\react-styleguidist\scripts\utils\StyleguidistOptionsPlugin.js:14:15)
    at SyncHook.eval [as call] (eval at create (c:\Data\Dev\CCSS\src\CCSS\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:17:12), <anonymous>:7:1)
    at SyncHook.lazyCompileHook [as _call] (c:\Data\Dev\CCSS\src\CCSS\node_modules\webpack\node_modules\tapable\lib\Hook.js:35:21)
    at Compiler.newCompilation (c:\Data\Dev\CCSS\src\CCSS\node_modules\webpack\lib\Compiler.js:451:26)
    at hooks.beforeCompile.callAsync.err (c:\Data\Dev\CCSS\src\CCSS\node_modules\webpack\lib\Compiler.js:487:29)
    at _err0 (eval at create (c:\Data\Dev\CCSS\src\CCSS\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:11:1)
    at compiler.hooks.beforeCompile.tapAsync (c:\Data\Dev\CCSS\src\CCSS\node_modules\webpack\lib\DllReferencePlugin.js:52:13)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (c:\Data\Dev\CCSS\src\CCSS\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (c:\Data\Dev\CCSS\src\CCSS\node_modules\webpack\node_modules\tapable\lib\Hook.js:35:21)
    at Compiler.compile (c:\Data\Dev\CCSS\src\CCSS\node_modules\webpack\lib\Compiler.js:482:28)
    at compiler.hooks.watchRun.callAsync.err (c:\Data\Dev\CCSS\src\CCSS\node_modules\webpack\lib\Watching.js:77:18)
    at _err0 (eval at create (c:\Data\Dev\CCSS\src\CCSS\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:38:1)
    at watchRun (c:\Data\Dev\CCSS\src\CCSS\node_modules\fork-ts-checker-webpack-plugin\lib\index.js:140:13)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (c:\Data\Dev\CCSS\src\CCSS\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (c:\Data\Dev\CCSS\src\CCSS\node_modules\webpack\node_modules\tapable\lib\Hook.js:35:21)
    at Watching._go (c:\Data\Dev\CCSS\src\CCSS\node_modules\webpack\lib\Watching.js:40:32)
listen EADDRINUSE 0.0.0.0:6060
```

Any assistance in troubleshooting appreciated.

**Comment by sapegin** [comment]
This is only a warning, Styleguidist works fine with webpack 4 (at least it used to work with older webpack 4 releases).

In any case we can't do anything without a reproducible demo.

**Comment by jamalsoueidan** [comment]
I had to delete both folders html-webpack-plugin and webpack-dev-server inside node_modules in react-styleguidist to get it work with webpack 4.

**Comment by jamalsoueidan** [comment]
Also in EditorLoader.js

```javascript
const file = source("lib", "rsg-components", "Editor", "EditorLoader.js");
const body = fs.readFileSync(file, "utf8");

fse.outputFile(file, body.replace("System.", "")).then(function() {
  console.log("Fix editorLoader.js");
});
```
