### ISSUE TITLE
react-native example for Babel 7.x

### ISSUE THREAD

**Issue by ProLoser** [styleguidist/react-styleguidist#1159]
The example is for Babel 6.x and unfortunately half the install targets in the example will be for Babel 7.x and the other half for 6.x

It would be nice if we either updated the example to work with the latest babel version or documented what dependencies are needed for use with babel 6

For example there's now `metro-react-native-babel-preset`, `@babel/core`, `@babel/preset-env` and other variations from the previous babel version that make recreating this example a bit of a headache.

**Comment by sapegin** [comment]
Feel free to send a pull request with updates!

**Comment by eragon512** [comment]
hey, is this issue available? if so, id like to take it up

**Comment by mcconkiee** [comment]
i'm still seeing this 
```
Trace: The node type SpreadProperty has been renamed to SpreadElement
    at Object.isSpreadProperty (/Users/ericmcconkie/Downloads/react-styleguidist-7.3.11/examples/react-native/node_modules/@babel/types/lib/validators/generated/index.js:4192:11)
    at hasSpread (/Users/ericmcconkie/Downloads/react-styleguidist-7.3.11/examples/react-native/node_modules/babel-plugin-transform-object-rest-spread/lib/index.js:38:13)
    at PluginPass.ObjectExpression (/Users/ericmcconkie/Downloads/react-styleguidist-7.3.11/examples/react-native/node_modules/babel-plugin-transform-object-rest-spread/lib/index.js:234:14)
    at newFn (/Users/ericmcconkie/Downloads/react-styleguidist-7.3.11/examples/react-native/node_modules/@babel/traverse/lib/visitors.js:193:21)
    at NodePath._call (/Users/ericmcconkie/Downloads/react-styleguidist-7.3.11/examples/react-native/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/ericmcconkie/Downloads/react-styleguidist-7.3.11/examples/react-native/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/ericmcconkie/Downloads/react-styleguidist-7.3.11/examples/react-native/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/Users/ericmcconkie/Downloads/react-styleguidist-7.3.11/examples/react-native/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (/Users/ericmcconkie/Downloads/react-styleguidist-7.3.11/examples/react-native/node_modules/@babel/traverse/lib/context.js:90:19)
    at TraversalContext.visit (/Users/ericmcconkie/Downloads/react-styleguidist-7.3.11/examples/react-native/node_modules/@babel/traverse/lib/context.js:146:19)
    at Function.traverse.node (/Users/ericmcconkie/Downloads/react-styleguidist-7.3.11/examples/react-native/node_modules/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (/Users/ericmcconkie/Downloads/react-styleguidist-7.3.11/examples/react-native/node_modules/@babel/traverse/lib/path/context.js:95:18)
    at TraversalContext.visitQueue (/Users/ericmcconkie/Downloads/react-styleguidist-7.3.11/examples/react-native/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitMultiple (/Users/ericmcconkie/Downloads/react-styleguidist-7.3.11/examples/react-native/node_modules/@babel/traverse/lib/context.js:85:17)
    at TraversalContext.visit (/Users/ericmcconkie/Downloads/react-styleguidist-7.3.11/examples/react-native/node_modules/@babel/traverse/lib/context.js:144:19)
    at Function.traverse.node (/Users/ericmcconkie/Downloads/react-styleguidist-7.3.11/examples/react-native/node_modules/@babel/traverse/lib/index.js:94:17)
...
```
is there possibly a conflict from my environment?

**Comment by ProLoser** [comment]
@mcconkiee you're seeing this when using @eragon512's version? It may make sense to create a new issue (can always reference this one) but I am unclear what steps you took to encounter this error.

**Comment by mcconkiee** [comment]
done: [#1201](https://github.com/styleguidist/react-styleguidist/issues/1201) - @ProLoser --- thanks
