### ISSUE TITLE
Unexpected token in code example

### ISSUE THREAD

**Issue by Sly36** [styleguidist/react-styleguidist#1321]
I had to install react-styleguidist with yarn (vs npm) to have PROPS & METHODSi working.

Now it works but i have Syntax errors for all my components (with defaultExample set to true and components with their own examples too):

in the .md file
```
``` jsx
<Card>test</Card>
```

results in

```
SyntaxError: Unexpected token (1:6)
1 : <React.Fragment><Card>test</Card></React.Fragment>;
          ^
```

and
```
``` jsx
// comment
<Card>test</Card>
```

results in

```
SyntaxError: Unexpected token (2:11)
1 : // comment
2 : <Card>test</Card>
               ^
```

here is an example of a simple component code :

```
import React from 'react';
import PropTypes from "prop-types";
import "../../../styles/elements/card.less"

const Card = ({children, id}) =>
    <div id={id} className={"Card"}>
        {children}
    </div>;

Card.propTypes = {
    id: PropTypes.string
};

export default Card;
```

**Comment by vollmerr** [comment]
I am getting this same error. Everything works fine on version 9.0.4, but get the above error on 9.0.5 for all my components.

**Comment by Sly36** [comment]
Thank you, downgrading to 9.0.4 fix the problem

**Comment by JonathanLehner** [comment]
downgrading works, but doesn't seem like a nice solution. what is the underlying issue?

**Comment by karsai5** [comment]
Having the same issue. Also 9.0.4 gets picked up as having vulnerabilities by npm audit which doesn't make it a super viable alternative.

**Comment by Betree** [comment]
It seems that this issue doesn't affect everyone so maybe we can get more info by sharing our configs. Below is ours, we use it with the following libraries (see the full list [here](https://github.com/opencollective/opencollective-frontend/blob/master/package.json)):
- `@babel/cli`: `7.1.2`
- `@babel/core`: `7.1.2`
- `@babel/node`: `7.0.0`
- `next`: `8.1.0`
- `react`: `16.8.6`

---

> https://github.com/opencollective/opencollective-frontend/blob/master/styleguide.config.js

```es6
const fs = require('fs');
const path = require('path');
const fileExistsCaseInsensitive = require('react-styleguidist/lib/scripts/utils/findFileCaseInsensitive');

module.exports = {
  assetsDir: 'styleguide',
  getExampleFilename(componentPath) {
    const parsedPath = path.parse(componentPath);
    const parentDirName = parsedPath.dir.split('src/components/')[1] || '';
    const parentDirPath = path.join(__dirname, 'styleguide', 'examples', parentDirName);

    if (!fs.existsSync(parentDirPath)) {
      return false;
    }

    const examplePath = path.join(parentDirPath, `${parsedPath.name}.md`);
    return fileExistsCaseInsensitive(examplePath) || false;
  },
  pagePerSection: true,
  moduleAliases: {
    components: path.resolve(__dirname, 'src/components'),
  },
  sections: [
    {
      name: 'Atoms',
      components: 'src/components/Styled*.js',
      description: 'Base design atoms.',
    },
    {
      name: 'UI',
      content: 'styleguide/pages/UI.md',
      components: 'src/components/*.js',
      ignore: ['src/components/Contribute*.js', 'src/components/Styled*.js', 'src/components/collective-page/*.js'],
    },
    {
      name: 'Collective Page',
      components: 'src/components/collective-page/*.js',
      description: 'These components are used on the donate/contribute flow.',
    },
    {
      name: 'Contribution Flow',
      components: 'src/components/Contribute*.js',
      description: 'These components are used on the donate/contribute flow.',
    },
    {
      name: 'Grid',
      content: 'styleguide/pages/Grid.md',
      sections: [
        {
          name: 'Box',
          content: 'styleguide/examples/Box.md',
        },
        {
          name: 'Flex',
          content: 'styleguide/examples/Flex.md',
        },
      ],
    },
  ],
  skipComponentsWithoutExample: true,
  styleguideComponents: {
    Wrapper: path.join(__dirname, 'styleguide/Wrapper'),
  },
  styles: {
    Blockquote: {
      blockquote: {
        borderLeft: '3px solid grey',
        margin: '16px 0',
        padding: '0 32px',
      },
    },
  },
  title: 'Open Collective Frontend Style Guide',
  usageMode: 'expand',
  webpackConfig: {
    resolve: { extensions: ['.js', '.json'] },
    stats: { children: false, chunks: false, modules: false, reasons: false },
    module: {
      rules: [
        {
          test: /\.(js|jsx)$/,
          exclude: /node_modules/,
          use: [{ loader: 'babel-loader', options: { cacheDirectory: true } }],
        },
        {
          test: /components\/.*\.(svg)$/,
          use: {
            loader: 'url-loader',
            options: {
              limit: 1000000,
            },
          },
        },
      ],
    },
  },
};
```

**Comment by WaldoJeffers** [comment]
I can confirm this, but it does not seem to be related to v9.0.4 or v9.0.5. I had the same issue without updating _any_ dependencies in my project. I simply did `rm -rf node_modules` followed by `yarn install`.

After some digging, it seems to be related to:
- https://github.com/acornjs/acorn/issues/792,
- which is itself related to https://github.com/eslint/eslint/issues/11018
- which was reported here https://npm.community/t/failed-to-install-eslint-in-a-specific-situation/2975



I got rid of it by upgrading all my `eslint-*` dependencies, but it's still a weird issue

**Comment by matsgm** [comment]
> I can confirm this, but it does not seem to be related to v9.0.4 or v9.0.5. I had the same issue without updating _any_ dependencies in my project. I simply did `rm -rf node_modules` followed by `yarn install`.
> 
> After some digging, it seems to be related to:
> 
> * [acornjs/acorn#792](https://github.com/acornjs/acorn/issues/792),
> * which is itself related to [eslint/eslint#11018](https://github.com/eslint/eslint/issues/11018)
> * which was reported here https://npm.community/t/failed-to-install-eslint-in-a-specific-situation/2975
> 
> I got rid of it by upgrading all my `eslint-*` dependencies, but it's still a weird issue

It looks like this fixed it :)

**Comment by karsai5** [comment]
Unfortunately upgrading eslint didn't fix it for me. But it seemed to be related to the version of `acorn` I had. Running the following worked for me:

* `npm update acorn --depth 20`
* `npm dedupe`

I suspect I had some dependency that was using the old version of acorn that was causing the problem.

**Comment by stoff** [comment]
Seeing this in a nascent project, currently very basic deps/config:
**package.json:**
```json
{
  "name": "fepdx-react-component-library",
  "version": "0.1.0",
  "description": "React components to encapsulate the design for FEPDX projects.",
  "main": "index.js",
  "scripts": {
    "start": "styleguidist server",
    "build": "rimraf dist && babel src --out-dir dist",
    "test": "jest"
  },
  "author": "Christoph Saxe",
  "license": "ISC",
  "dependencies": {
    "@emotion/core": "^10.0.10",
    "emotion-theming": "^10.0.10",
    "prop-types": "^15.7.2",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-styleguidist": "^9.1.2",
    "webpack": "^4.32.2"
  },
  "devDependencies": {
    "@babel/cli": "^7.4.4",
    "@babel/core": "^7.4.5",
    "@babel/preset-env": "^7.4.5",
    "@babel/preset-react": "^7.0.0",
    "@emotion/babel-preset-css-prop": "^10.0.9",
    "babel-jest": "^24.8.0",
    "babel-loader": "^8.0.6",
    "jest": "^24.8.0",
    "react-test-renderer": "^16.8.6",
    "rimraf": "^2.6.3"
  }
}
```
**styleguide.config.js:**
```js
module.exports = {
  webpackConfig: {
    module: {
      rules: [
        {
          test: /\.js?$/,
          exclude: /node_modules/,
          loader: 'babel-loader',
        }
      ]
    }
  },
  components: 'src/components/**/[A-Z]*.js',
};
```

**Comment by ManishBobde** [comment]
Hi All,
Do we have any fix for the open issue ?

**Comment by michaelkutuzov** [comment]
I have same problem. All methods from this thread don't help😞

**Comment by antonin87** [comment]
Same problem here :( Try all the methods but still not work. Any tips ?

**Comment by tonyjeffrey** [comment]
I have the same problem. 9.0.4 works but 9.0.5 have the error.

**Comment by cisen** [comment]
```
yarn add acorn acorn-jsx
```
It works for me!

**Comment by swashcap** [comment]
Changing from npm to [yarn](https://yarnpkg.com/en/) solved this problem in my project. Seems like something's wrong in the dependency tree? https://github.com/styleguidist/react-styleguidist/issues/1321#issuecomment-494732909 and other comments on this issue indicate this.

**Comment by roblevintennis** [comment]
Yeah, I fixed it by doing the downgrade with:
`yarn add --dev --exact react-styleguidist@9.0.4`

**Comment by svetogor** [comment]
Downgrade didn't work for me.
Tried to upgrade/downgrade `react-styleguidist`, `acorn`, `acorn-jsx`, `@babel/core` and its plugins...
Completely remove both `node_modules` and `package-lock.json` didn't help either.

Still getting
```
SyntaxError: Unexpected token (1:6)
1 : <React.Fragment>
```

Any other ideas?

**Comment by cicely-f** [comment]
still happening with 9.1.16. the components are in tsx. the styleguide config is only specifying sections/components, and tsconfig is as follows:
```
{
  "compilerOptions": {
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "downlevelIteration": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "module": "esnext",
    "moduleResolution": "node",
    "noEmit": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "strict": true,
    "target": "es5"
  },
  "include": [
    "src"
  ]
}
```

**Comment by dustin-ruetz** [comment]
I was experiencing the same "unexpected token" issue in all of my .md React component examples in one of my libraries when using the latest version of `react-styleguidist` (currently 9.1.16).

To expand on @cisen's fix posted above, I determined that the issue was with the latest version of `acorn` (currently 7.0.0). Explicitly installing the latest 6.* version of `acorn` (currently 6.3.0) as a dev dependency fixed the issue for me.

Specific steps:

```sh
# remove dependencies and delete lock file
rm -rf node_modules && rm -rf package-lock.json

# install + add acorn to devDependencies
npm install --save-dev acorn@^6.3.0

# re-install everything from package.json
npm install
```

Additional context:

- I didn't want to switch my entire local/CI workflow from NPM to Yarn; and
- I couldn't rollback to a previous version of `react-styleguidist` because I depend on using React hooks in my code examples.

**Comment by rafegoldberg** [comment]
> **Steps**
> 
> # remove dependencies and delete lock file
> rm -rf node_modules && rm -rf package-lock.json
> 
> # install + add acorn to devDependencies
> npm install --save-dev acorn@^6.3.0
> 
> # re-install everything from package.json
> npm install

@dustin-ruetz's solution worked for me!

**Comment by josias-r** [comment]
It worked for me as well. It's important to remove the lock file and node_modules though... So I guess it's an issue in the dependency tree of react-styleguidist?

**Comment by adrienharnay** [comment]
Also facing the same issue. I tried:
- [installing acorn & acorn-jsx](https://github.com/styleguidist/react-styleguidist/issues/1321#issuecomment-516210699)
- [installing acorn@6.3.0](https://github.com/styleguidist/react-styleguidist/issues/1321#issuecomment-523474993)
- other tricks
Nothing fixed it for me

**Comment by kingkomg** [comment]
installing with yarn worked for me. hat the same problem with versions 9.1.14 and 9.1.16

**Comment by codler** [comment]
I have the same problem in v9.1.16

**Comment by elstr** [comment]
> I have the same problem in v9.1.16

This solved the issue for me `rm -rf node_modules && npm install --legacy-bundling`

**Comment by blumendorf** [comment]
Experienced the issue on v9.1.16 after updating other dependencies.
`styleguidist server` worked, while `styleguidist build` didn't.

[installing acorn@6.3.0
](https://github.com/styleguidist/react-styleguidist/issues/1321#issuecomment-523474993) fixed it for me.

It might be related to eslint requiring acorn 7.0.0?

`"eslint": {
   "version": "6.5.1",
   "requires": {
     "espree": "^6.1.1",
     ...
   }
}
"espree": {
  "version": "6.1.1",
  "requires": {
    "acorn": "^7.0.0",
    "acorn-jsx": "^5.0.2",
    "eslint-visitor-keys": "^1.1.0"
  },
  "dependencies": {
    "acorn": {
      "version": "7.1.0",
    }
  }
}
 `

**Comment by MacZel** [comment]
same for me :(

**Comment by malyzeli** [comment]
Seems that explicitly installing `acorn` helps, but it didn't work for me until I cleared npm cache.

```sh
npm cache clean --force
rm -rf node_modules package-lock.js
npm install --save-dev acorn@6
npm install
```

**Comment by sapegin** [comment]
I guess some of your project dependencies depends on Acorn 7, because Styleguidist depends only on 6.x. And all the solutions above is how to trick npm/yarn to use Acorn 6 with Stylegudist.

And help with _actually_ fixing the issue is very much appreciated.

**Comment by sapegin** [comment]
Buble doesn't support Acorn 7:

https://github.com/bublejs/buble/blob/2da2ddb00f751a266fa07759a370a99059e21ce6/package.json#L73

And looks like something weird is happening when Acorn 7 is in the dependency tree. Buble tries to use Acorn 6 from its own `node_modules` but it doesn't work for some reason. Here might be some difference in module resolution between npm and Yarn, and why Yarn works when npm doesn't.

I've made a simple failing test:

*package.json*:

```json
{
  "name": "acorn-test",
  "private": true,
  "dependencies": {
    "acorn": "7.1.0",
    "acorn-jsx": "5.1.0",
    "buble": "0.19.8"
  }
}
```

*test.js*:

```js
var buble = require('buble');
var result = buble.transform(`<Button />`);
```

And when I run `node test.js` I see an error:

```
SyntaxError: Unexpected token (1:8)
    at Object.pp$4.raise (/Users/asapegin/klsdafafs/node_modules/buble/node_modules/acorn/dist/acorn.js:2825:15)
    at Object.pp.unexpected (/Users/asapegin/klsdafafs/node_modules/buble/node_modules/acorn/dist/acorn.js:689:10)
    at Object.jsx_parseIdentifier (/Users/asapegin/klsdafafs/node_modules/acorn-jsx/index.js:249:14)
    at Object.jsx_parseNamespacedName (/Users/asapegin/klsdafafs/node_modules/acorn-jsx/index.js:258:23)
    at Object.jsx_parseAttribute (/Users/asapegin/klsdafafs/node_modules/acorn-jsx/index.js:335:24)
    at Object.jsx_parseOpeningElementAt (/Users/asapegin/klsdafafs/node_modules/acorn-jsx/index.js:348:35)
    at Object.jsx_parseElementAt (/Users/asapegin/klsdafafs/node_modules/acorn-jsx/index.js:370:33)
    at Object.jsx_parseElement (/Users/asapegin/klsdafafs/node_modules/acorn-jsx/index.js:428:19)
    at Object.parseExprAtom (/Users/asapegin/klsdafafs/node_modules/acorn-jsx/index.js:435:21)
    at Object.pp$3.parseExprSubscripts (/Users/asapegin/klsdafafs/node_modules/buble/node_modules/acorn/dist/acorn.js:2089:21)
```

Looks at the stack trace I see that Buble uses Acorn 6.3.0 from it's own dependencies but it fails anyway. But looks like acorn-jsx will use whatever the latest version of Acorn is available in the tree.

**Comment by sapegin** [comment]
Also Buble seems to be in maintenance mode now, so we should consider migrating to something else:

https://github.com/bublejs/buble/issues/220

**Comment by iansan5653** [comment]
I've been trying to narrow the problem down a bit more:

The test you posted still fails when `package.json` is:
```json
{
  "name": "acorn-test",
  "private": true,
  "dependencies": {
    "acorn": "^7.1.0",
    "buble": "0.19.8"
  }
}
```

`acorn-jsx` has the following dependency:
```json
  "peerDependencies": {
    "acorn": "^6.0.0 || ^7.0.0"
  },
```

So when `buble` uses the `acorn-jsx` plugin to extend `acorn`, `acorn-jsx` is perfectly OK with pulling in the `^7.1.0` version instead of `6`, and this causes the problem. So `buble` (and any other module that is not compatible with `acorn^7.0.0`, should be relying not on `acorn-jsx^5.0.0`, but on `^4.0.0`. 

In short this is definitely something that should be fixed upstream.

**Comment by iansan5653** [comment]
A possible fix here would be to lock `buble` to `=0.19.4` which is the most recent version that depended on `acorn^4.0.0`.  Not the prettiest solution but it would fix the problem until you're able to move away from Buble altogether.

**Comment by malyzeli** [comment]
> Also Buble seems to be in maintenance mode now, so we should consider migrating to something else:
> 
> [bublejs/buble#220](https://github.com/bublejs/buble/issues/220)

@sapegin Sorry for offtopic considering scope of this issue but what is the reason for using something like `buble` instead of battle-tested `babel`? Don't have to explain here - if there are any articles/discussions related to this question, just point me there and I will read it. Thank you!

**Comment by sapegin** [comment]
@malyzeli Primarily its size: babel-standalone is gigantic and we'll need to find a way to lazy load it somehow which is tricky because we need it to render all the examples.

**Comment by JustFly1984** [comment]
We also have same issue. https://react-google-maps-api-docs.netlify.com/ Nothing helps.

**Comment by sapegin** [comment]
@JustFly1984 This kind of comments don't add anything to the discussion and significantly contribute to maintainers burnout. Now I have to either lock this thread to prevent future spam comment, which will also prevent folks who are actually trying to help from posting useful comments. Or unsubscribe myself to stop receiving spam comments — my own mental health is definitely more important to me than someone's problem with their project.

**Comment by JustFly1984** [comment]
@sapegin sorry mate, I didn't mean to be rude. I use your open source project in my open source project.

I'm building my project with tsdx, and it has acorn@7 in dependencies, so I can't add acorn@6.3.0 to resolution in package.json, cos it breaks build.

**Comment by iansan5653** [comment]
Looks like acorn/axornjsx#887 fixed this! Since the release of `acorn@6.4.0` I'm able to run the test that @sapegin posted, and after running `npm update acorn --depth 20` in my project, I'm able to use Styleguidist again. ❤️

**Comment by sergdenisov** [comment]
@iansan5653 I've made that fix in https://github.com/styleguidist/react-styleguidist/pull/1495.

**Comment by Betree** [comment]
Fix worked for us. Thanks!

**Comment by iamchathu** [comment]
Tried it. Still have the issue `"react-styleguidist": "^10.6.1"`

**Comment by JustFly1984** [comment]
@iamchathu check if you have semicolons everywhere. I had issues with files until I’ve set semicolons in place. This is not obvious, and it could be helpful if there was no semicolons required.

**Comment by iamchathu** [comment]
@JustFly1984 I'm using to prettier rules to set semi colons and I double checked but seems there is an issue yet.
