### ISSUE TITLE
assetsDir broken in 11.0.9 with create-react-app

### ISSUE THREAD

**Issue by stufisher** [styleguidist/react-styleguidist#1676]
**Current behavior**

After updating to 11.0.9 it is no longer possible to build the styleguide if using assetsDir (which invokes the webpack copy plugin)

**To reproduce**

`styleguideist build`

```
Building style guide...
ValidationError: Invalid options object. Copy Plugin has been initialized using an options object that does not match the API schema.
 - options[0] misses the property 'patterns'. Should be:
   [non-empty string | object { from, to?, context?, globOptions?, filter?, toType?, force?, flatten?, transform?, cacheTransform?, transformPath?, noErrorOnMissing? }, ...] (should not have fewer than 1 item)
ValidationError: Invalid options object. Copy Plugin has been initialized using an options object that does not match the API schema.
 - options[0] misses the property 'patterns'. Should be:
   [non-empty string | object { from, to?, context?, globOptions?, filter?, toType?, force?, flatten?, transform?, cacheTransform?, transformPath?, noErrorOnMissing? }, ...] (should not have fewer than 1 item)
    at validate (.../node_modules/react-styleguidist/node_modules/schema-utils/dist/validate.js:98:11)
    at new CopyPlugin (.../node_modules/react-styleguidist/node_modules/copy-webpack-plugin/dist/index.js:32:30)
    at _default (.../node_modules/react-styleguidist/lib/scripts/make-webpack-config.js:114:34)
    at build (.../node_modules/react-styleguidist/lib/scripts/build.js:13:63)
    at commandBuild (.../node_modules/react-styleguidist/lib/bin/styleguidist.js:105:20)
    at Object.<anonymous> (.../node_modules/react-styleguidist/lib/bin/styleguidist.js:71:5)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

```
If i remove
`assetsDir: 'src/assets/images/',`

Then all builds as normal. I noticed webpack copy plugin has been updated to 6.0.x, downgrading this alone to 5.x.x does not fix the issue. 

Downgrading styleguidist to 11.0.8 does allow the styleguide to build.

**Expected behavior**

Styleguide should build

**Comment by sapegin** [comment]
That's weird that downgrading back doesn't help. Is it possible that it's still cached and you still have the new version?

Mind checking [changelog](https://github.com/webpack-contrib/copy-webpack-plugin/releases/tag/v6.0.0) to see if we need to upgrade any configuration? A pull request would be awesome 👾

**Comment by lefreet** [comment]
@sapegin it's a broken update in [copy-webpack-plugin](https://github.com/webpack-contrib/copy-webpack-plugin/releases/tag/v6.0.0), but not update with [make-webpack-config](https://github.com/styleguidist/react-styleguidist/blob/382e3ade4f59762f3f4c828d37124ba6dcf1e9b3/src/scripts/make-webpack-config.ts#L112)

**Comment by lefreet** [comment]
see with https://github.com/styleguidist/react-styleguidist/commit/53bc4bb357133e2208ca28e5181b44306fdc4e3d

**Comment by swashata** [comment]
I would like to take a crack at this, if anyone else is not already working.

**Comment by swashata** [comment]
Pull Request #1690 is ready. I have also tested it with linking to my local project and it works fine. @sapegin kindly review at your convenience.
