### ISSUE TITLE
Failing to run styleguidist server on react library project

### ISSUE THREAD

**Issue by danielc92** [styleguidist/react-styleguidist#1832]
Hey I've been trying to integrate this package into an existing react/typescript project. Used some configs from the example

**error:** 
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'styleguidist',
1 verbose cli   'server'
1 verbose cli ]
2 info using npm@6.14.13
3 info using node@v14.17.0
4 verbose run-script [ 'prestyleguidist', 'styleguidist', 'poststyleguidist' ]
5 info lifecycle react-docgen-typescript-example@0.0.1~prestyleguidist: react-docgen-typescript-example@0.0.1
6 info lifecycle react-docgen-typescript-example@0.0.1~styleguidist: react-docgen-typescript-example@0.0.1
7 verbose lifecycle react-docgen-typescript-example@0.0.1~styleguidist: unsafe-perm in lifecycle true
8 verbose lifecycle react-docgen-typescript-example@0.0.1~styleguidist: PATH: C:\Users\dc\AppData\Roaming\nvm\v14.17.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\dc\Desktop\chyea\examples\react-styleguidist-example\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\Git\cmd;C:\Users\dc\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Users\dc\AppData\Local\Programs\Python\Python36\Scripts\;C:\Users\dc\AppData\Local\Programs\Python\Python36\;C:\Users\dc\AppData\Local\Microsoft\WindowsApps;C:\Users\dc\AppData\Roaming\nvm;C:\Program Files\nodejs
9 verbose lifecycle react-docgen-typescript-example@0.0.1~styleguidist: CWD: C:\Users\dc\Desktop\chyea\examples\react-styleguidist-example
10 silly lifecycle react-docgen-typescript-example@0.0.1~styleguidist: Args: [ '/d /s /c', 'styleguidist "server"' ]
11 silly lifecycle react-docgen-typescript-example@0.0.1~styleguidist: Returned: code: 1  signal: null
12 info lifecycle react-docgen-typescript-example@0.0.1~styleguidist: Failed to exec styleguidist script
13 verbose stack Error: react-docgen-typescript-example@0.0.1 styleguidist: `styleguidist "server"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\dc\AppData\Roaming\nvm\v14.17.0\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:376:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\dc\AppData\Roaming\nvm\v14.17.0\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:376:20)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid react-docgen-typescript-example@0.0.1
15 verbose cwd C:\Users\dc\Desktop\chyea\examples\react-styleguidist-example
16 verbose Windows_NT 10.0.19041
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "styleguidist" "server"
18 verbose node v14.17.0
19 verbose npm  v6.14.13
20 error code ELIFECYCLE
21 error errno 1
22 error react-docgen-typescript-example@0.0.1 styleguidist: `styleguidist "server"`
22 error Exit status 1
23 error Failed at the react-docgen-typescript-example@0.0.1 styleguidist script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**webpack config**
```
var path = require('path');

module.exports = {
  entry: {
      bundle: ['./src/index.ts'],
  },
  context: path.resolve(__dirname),
  output: {
    filename: 'bundle.js',
    path: path.join(__dirname, 'temp')
  },
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        loader: 'ts-loader',
        exclude: /node_modules/,
      }
    ]
  },
  resolve: {
    extensions: [".tsx", ".ts", ".js"]
  }
};
```
**tsconfig.json**
```
{
  "compilerOptions": {
    "rootDir": "./src",
    "baseUrl": "./src",
    "paths": {
      "#/*": ["./*"]
    },
    "declaration": true,
    "declarationDir": "build",
    "module": "esnext",
    "target": "es5",
    "lib": ["es6", "dom", "es2016", "es2017"],
    "sourceMap": true,
    "jsx": "react",
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true
  },
  "include": ["src"],
  "exclude": [
    "node_modules",
    "build",
    "storybook-static"
  ]
}

```

**styleguidist.config.js**
```
const path = require('path');
const glob = require('glob');

module.exports = {
  title: 'React Style Guide Example',
  //   components() {
  //     return glob
  //       .sync(path.resolve(__dirname, 'src/components/**/*.tsx'))
  //       .filter((module) => /\/[A-Z]\w*\.tsx$/.test(module));
  //   },
  components: 'src/components/**/[A-Z]*.tsx',
  resolver: require('react-docgen').resolver.findAllComponentDefinitions,
  propsParser: require('react-docgen-typescript').withCustomConfig(
    './tsconfig.json'
  ).parse,
  ignore: ['**/*.test.tsx', '**/*.stories.tsx'],
};

```

**github branch**
(using node v14.17.0)
https://github.com/danielc92/dc-react-ui/tree/experiment/auto-docs

**Comment by danielc92** [comment]
ive managed to resolve this

**Comment by carltian** [comment]
@ 

> ive managed to resolve this

same issue, how do you resolve this?
