### ISSUE TITLE
Cannot require CSS polyfill

### ISSUE THREAD

**Issue by boldfacedesign** [styleguidist/react-styleguidist#575]
I'm trying to include a stylesheet as per https://react-styleguidist.js.org/docs/cookbook.html#how-to-add-custom-javascript-and-css-or-polyfills

Whilst this seems to work for `.js` files I get the following error with `.css` requires:

```
/node_modules/react-styleguidist/bin/styleguidist.js:31
		throw err;
		^

TypeError: Cannot read property '1' of null
    at printNoLoaderError (/node_modules/react-styleguidist/bin/styleguidist.js:228:58)
    at printAllErrors (/node_modules/react-styleguidist/bin/styleguidist.js:195:2)
    at printAllErrorsAndWarnings (/node_modules/react-styleguidist/bin/styleguidist.js:181:3)
    at Compiler.<anonymous> (/node_modules/react-styleguidist/bin/styleguidist.js:96:21)
    at Compiler.applyPlugins (/node_modules/tapable/lib/Tapable.js:61:14)
    at emitRecords.err (/node_modules/webpack/lib/Compiler.js:268:11)
    at Compiler.emitRecords (/node_modules/webpack/lib/Compiler.js:375:38)
    at emitAssets.err (/node_modules/webpack/lib/Compiler.js:262:10)
    at applyPluginsAsyncSeries1.err (/node_modules/webpack/lib/Compiler.js:368:12)
    at next (/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at next (/node_modules/tapable/lib/Tapable.js:220:14)
    at callback (/node_modules/copy-webpack-plugin/dist/index.js:108:17)
    at Compiler.<anonymous> (/node_modules/copy-webpack-plugin/dist/index.js:131:13)
    at Compiler.applyPluginsAsyncSeries1 (/node_modules/tapable/lib/Tapable.js:222:13)
    at Compiler.afterEmit (/node_modules/webpack/lib/Compiler.js:365:9)
    at require.forEach.err (/node_modules/webpack/lib/Compiler.js:360:15)
    at /node_modules/async/dist/async.js:421:16
    at iteratorCallback (/node_modules/async/dist/async.js:998:13)
    at /node_modules/async/dist/async.js:906:16
    at /node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:112:15)
```

Appears to be related to #323

**Comment by boldfacedesign** [comment]
Figured this out. My project uses `less` and my main webpack config (which is used by styleguidist by default) only has a test and loader setup for `.less` and not `.css`

**Comment by sapegin** [comment]
Looks like we have a bug in a function that should print a messages that you don’t have a loader ;-?
