### ISSUE TITLE
Issue with recognizing es6-notation in type-detect dependency

### ISSUE THREAD

**Issue by 1cc** [styleguidist/react-styleguidist#683]
When I run or build the styleguide with npm, I get the following error:

\node_modules\type-detect\index.js:49
 export default function typeDetect(obj) {
 ^^^^^^

SyntaxError: Unexpected token export
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)

The problem seems that the es6 notation in the dependency type-detect isn't recognized. By changing this to a function in the old notation in the module itself, it works again. But this is kind of a hack. Is there a way to solve this problem?

Webpack version is 2.6.1

**Comment by sapegin** [comment]
It was fixed already, remove `package-lock.json` and reinstall your dependencies.
