### ISSUE TITLE
Error: Error watching file for changes: EMFILE when running test on new Create React App

### ISSUE THREAD

**Issue by robbie-hinman** [styleguidist/react-styleguidist#872]
Firstly, **thank you for such a great tool**!  

Posting this because we are getting the following error when running either `yarn test` or `npm test`:

> 2018-03-14 16:23 node[5933] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2018-03-14 16:23 node[5933] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
events.js:183
      throw er; // Unhandled 'error' event
      ^
>
> Error: Error watching file for changes: EMFILE
    at _errnoException (util.js:1022:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1351:9)
error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

The steps to reproduce are:
1. Using node version 8.9.4... (also seen in 8.8.1, and 7.7.1)
2. create a brand new Create-react-app (currently this means installing react-scripts 1.1.1)
3. run `yarn test` (observe no issues)
4. run `yarn add react-styleguidist`
5. run `yarn test` (observe above error)

I have a demo repo setup with state after step 4 [here](https://github.com/robbie-hinman/styleguidist-issue).  This does not fork the example repo since the issue is using styleguidist with CRA, which the demo repo does not include.

I am on mac (10.12.6) and my yarn version is 1.3.2.

**Comment by robbie-hinman** [comment]
This looks like a Jest issue according to: facebook/create-react-app#871
