### ISSUE TITLE
Investigate flacky Cypress test

### ISSUE THREAD

**Issue by sapegin** [styleguidist/react-styleguidist#895]
```
  1) Single component preview section changes the render after code change:
     CypressError: Timed out retrying: Expected to find content: 'Push Me Harder' within the element: <button.button> but never did.
      at Object.cypressErr (http://localhost:8082/__cypress/runner/cypress_runner.js:67227:11)
      at Object.throwErr (http://localhost:8082/__cypress/runner/cypress_runner.js:67192:18)
      at Object.throwErrByPath (http://localhost:8082/__cypress/runner/cypress_runner.js:67219:17)
      at retry (http://localhost:8082/__cypress/runner/cypress_runner.js:61228:16)
      at http://localhost:8082/__cypress/runner/cypress_runner.js:53731:18
      at tryCatcher (http://localhost:8082/__cypress/runner/cypress_runner.js:7091:23)
      at Promise._settlePromiseFromHandler (http://localhost:8082/__cypress/runner/cypress_runner.js:5113:31)
      at Promise._settlePromise (http://localhost:8082/__cypress/runner/cypress_runner.js:5170:18)
      at Promise._settlePromise0 (http://localhost:8082/__cypress/runner/cypress_runner.js:5215:10)
      at Promise._settlePromises (http://localhost:8082/__cypress/runner/cypress_runner.js:5290:18)
      at Async._drainQueue (http://localhost:8082/__cypress/runner/cypress_runner.js:2023:16)
      at Async._drainQueues (http://localhost:8082/__cypress/runner/cypress_runner.js:2033:10)
      at Async.drainQueues (http://localhost:8082/__cypress/runner/cypress_runner.js:1907:14)
      at <anonymous>
```

**Comment by sapegin** [comment]
Sould be fixed in #1073.
